# Javascript Node CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.4
      - image: circleci/mongo:3.6
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:10.4
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "12:7f:90:a4:10:4e:f9:91:84:b8:de:ea:7e:51:f8:58"
      - run:
          name: clever deploy
          command: |
            ssh-keyscan -H $CLEVER_KNOWN_HOST >> ~/.ssh/known_hosts
            git remote add clever $CLEVER_REMOTE
            git push clever master 
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
